// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Randevu365.Persistence.Context;

#nullable disable

namespace Randevu365.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309113148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Randevu365.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserInformationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserInformationId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserInformationId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$iTswnw/5VyzC43Wy13w9vOTPQ.rwl6BZjcx3pH5XUdsGhzEwmVPNS",
                            Role = "Administrator",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AppUserInformationId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner1@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$Rqi6dTA8Q42o/eCnzg9prOPAPj2tRB3SX5O5HneHtE2w85nv4VKP.",
                            Role = "BusinessOwner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AppUserInformationId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner2@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$Rqi6dTA8Q42o/eCnzg9prOPAPj2tRB3SX5O5HneHtE2w85nv4VKP.",
                            Role = "BusinessOwner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AppUserInformationId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner3@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$Rqi6dTA8Q42o/eCnzg9prOPAPj2tRB3SX5O5HneHtE2w85nv4VKP.",
                            Role = "BusinessOwner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AppUserInformationId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner4@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$Rqi6dTA8Q42o/eCnzg9prOPAPj2tRB3SX5O5HneHtE2w85nv4VKP.",
                            Role = "BusinessOwner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AppUserInformationId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner5@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$Rqi6dTA8Q42o/eCnzg9prOPAPj2tRB3SX5O5HneHtE2w85nv4VKP.",
                            Role = "BusinessOwner",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AppUserInformationId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$IGW3Vm5qpmfE4a.Yf2qUXuoeZL72Yl7SSljF1zpU00THU4a8h97kO",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AppUserInformationId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$IGW3Vm5qpmfE4a.Yf2qUXuoeZL72Yl7SSljF1zpU00THU4a8h97kO",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AppUserInformationId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer3@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$IGW3Vm5qpmfE4a.Yf2qUXuoeZL72Yl7SSljF1zpU00THU4a8h97kO",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AppUserInformationId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer4@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$IGW3Vm5qpmfE4a.Yf2qUXuoeZL72Yl7SSljF1zpU00THU4a8h97kO",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AppUserInformationId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer5@randevu365.com",
                            IsDeleted = false,
                            Password = "$2a$11$IGW3Vm5qpmfE4a.Yf2qUXuoeZL72Yl7SSljF1zpU00THU4a8h97kO",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.AppUserInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppUserInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Admin",
                            PhoneNumber = "05001234567",
                            Surname = "Randevu365",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ahmet",
                            PhoneNumber = "05321234567",
                            Surname = "Yılmaz",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Elif",
                            PhoneNumber = "05331234567",
                            Surname = "Kaya",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Mehmet",
                            PhoneNumber = "05341234567",
                            Surname = "Demir",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ayşe",
                            PhoneNumber = "05351234567",
                            Surname = "Çelik",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Ali",
                            PhoneNumber = "05361234567",
                            Surname = "Öztürk",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Zeynep",
                            PhoneNumber = "05371234567",
                            Surname = "Arslan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Burak",
                            PhoneNumber = "05381234567",
                            Surname = "Doğan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Seda",
                            PhoneNumber = "05391234567",
                            Surname = "Kılıç",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Emre",
                            PhoneNumber = "05401234567",
                            Surname = "Aslan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Merve",
                            PhoneNumber = "05411234567",
                            Surname = "Çetin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("ApproveEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("ApproveStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("BusinessServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("RequestedEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("RequestedStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BusinessServiceId");

                    b.HasIndex("BusinessId", "AppointmentDate", "RequestedStartTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BusinessCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BusinessCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BusinessCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BusinessPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 2,
                            BusinessAddress = "Dummy Adres No:1",
                            BusinessCategory = "kuafor",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner1@randevu365.com",
                            BusinessName = "Business Owner 1 - İşletme 1",
                            BusinessPhone = "02120000001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 2,
                            BusinessAddress = "Dummy Adres No:2",
                            BusinessCategory = "kuafor",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner1@randevu365.com",
                            BusinessName = "Business Owner 1 - İşletme 2",
                            BusinessPhone = "02120000002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 2,
                            BusinessAddress = "Dummy Adres No:3",
                            BusinessCategory = "kuafor",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner1@randevu365.com",
                            BusinessName = "Business Owner 1 - İşletme 3",
                            BusinessPhone = "02120000003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 2,
                            BusinessAddress = "Dummy Adres No:4",
                            BusinessCategory = "kuafor",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner1@randevu365.com",
                            BusinessName = "Business Owner 1 - İşletme 4",
                            BusinessPhone = "02120000004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 2,
                            BusinessAddress = "Dummy Adres No:5",
                            BusinessCategory = "kuafor",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner1@randevu365.com",
                            BusinessName = "Business Owner 1 - İşletme 5",
                            BusinessPhone = "02120000005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 3,
                            BusinessAddress = "Dummy Adres No:6",
                            BusinessCategory = "guzellik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner2@randevu365.com",
                            BusinessName = "Business Owner 2 - İşletme 1",
                            BusinessPhone = "02120000006",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = 3,
                            BusinessAddress = "Dummy Adres No:7",
                            BusinessCategory = "guzellik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner2@randevu365.com",
                            BusinessName = "Business Owner 2 - İşletme 2",
                            BusinessPhone = "02120000007",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = 3,
                            BusinessAddress = "Dummy Adres No:8",
                            BusinessCategory = "guzellik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner2@randevu365.com",
                            BusinessName = "Business Owner 2 - İşletme 3",
                            BusinessPhone = "02120000008",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = 3,
                            BusinessAddress = "Dummy Adres No:9",
                            BusinessCategory = "guzellik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner2@randevu365.com",
                            BusinessName = "Business Owner 2 - İşletme 4",
                            BusinessPhone = "02120000009",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = 3,
                            BusinessAddress = "Dummy Adres No:10",
                            BusinessCategory = "guzellik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner2@randevu365.com",
                            BusinessName = "Business Owner 2 - İşletme 5",
                            BusinessPhone = "02120000010",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = 4,
                            BusinessAddress = "Dummy Adres No:11",
                            BusinessCategory = "saglik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner3@randevu365.com",
                            BusinessName = "Business Owner 3 - İşletme 1",
                            BusinessPhone = "02120000011",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AppUserId = 4,
                            BusinessAddress = "Dummy Adres No:12",
                            BusinessCategory = "saglik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner3@randevu365.com",
                            BusinessName = "Business Owner 3 - İşletme 2",
                            BusinessPhone = "02120000012",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            AppUserId = 4,
                            BusinessAddress = "Dummy Adres No:13",
                            BusinessCategory = "saglik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner3@randevu365.com",
                            BusinessName = "Business Owner 3 - İşletme 3",
                            BusinessPhone = "02120000013",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            AppUserId = 4,
                            BusinessAddress = "Dummy Adres No:14",
                            BusinessCategory = "saglik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner3@randevu365.com",
                            BusinessName = "Business Owner 3 - İşletme 4",
                            BusinessPhone = "02120000014",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            AppUserId = 4,
                            BusinessAddress = "Dummy Adres No:15",
                            BusinessCategory = "saglik",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner3@randevu365.com",
                            BusinessName = "Business Owner 3 - İşletme 5",
                            BusinessPhone = "02120000015",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            AppUserId = 5,
                            BusinessAddress = "Dummy Adres No:16",
                            BusinessCategory = "fitness",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner4@randevu365.com",
                            BusinessName = "Business Owner 4 - İşletme 1",
                            BusinessPhone = "02120000016",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            AppUserId = 5,
                            BusinessAddress = "Dummy Adres No:17",
                            BusinessCategory = "fitness",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner4@randevu365.com",
                            BusinessName = "Business Owner 4 - İşletme 2",
                            BusinessPhone = "02120000017",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            AppUserId = 5,
                            BusinessAddress = "Dummy Adres No:18",
                            BusinessCategory = "fitness",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner4@randevu365.com",
                            BusinessName = "Business Owner 4 - İşletme 3",
                            BusinessPhone = "02120000018",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            AppUserId = 5,
                            BusinessAddress = "Dummy Adres No:19",
                            BusinessCategory = "fitness",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner4@randevu365.com",
                            BusinessName = "Business Owner 4 - İşletme 4",
                            BusinessPhone = "02120000019",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            AppUserId = 5,
                            BusinessAddress = "Dummy Adres No:20",
                            BusinessCategory = "fitness",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner4@randevu365.com",
                            BusinessName = "Business Owner 4 - İşletme 5",
                            BusinessPhone = "02120000020",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            AppUserId = 6,
                            BusinessAddress = "Dummy Adres No:21",
                            BusinessCategory = "dis",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner5@randevu365.com",
                            BusinessName = "Business Owner 5 - İşletme 1",
                            BusinessPhone = "02120000021",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            AppUserId = 6,
                            BusinessAddress = "Dummy Adres No:22",
                            BusinessCategory = "dis",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner5@randevu365.com",
                            BusinessName = "Business Owner 5 - İşletme 2",
                            BusinessPhone = "02120000022",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            AppUserId = 6,
                            BusinessAddress = "Dummy Adres No:23",
                            BusinessCategory = "dis",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner5@randevu365.com",
                            BusinessName = "Business Owner 5 - İşletme 3",
                            BusinessPhone = "02120000023",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            AppUserId = 6,
                            BusinessAddress = "Dummy Adres No:24",
                            BusinessCategory = "dis",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner5@randevu365.com",
                            BusinessName = "Business Owner 5 - İşletme 4",
                            BusinessPhone = "02120000024",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            AppUserId = 6,
                            BusinessAddress = "Dummy Adres No:25",
                            BusinessCategory = "dis",
                            BusinessCity = "İstanbul",
                            BusinessCountry = "Türkiye",
                            BusinessEmail = "owner5@randevu365.com",
                            BusinessName = "Business Owner 5 - İşletme 5",
                            BusinessPhone = "02120000025",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 7,
                            BusinessId = 1,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 8,
                            BusinessId = 2,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 9,
                            BusinessId = 2,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 9,
                            BusinessId = 3,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 10,
                            BusinessId = 4,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 11,
                            BusinessId = 4,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = 11,
                            BusinessId = 5,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = 7,
                            BusinessId = 6,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = 8,
                            BusinessId = 6,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = 8,
                            BusinessId = 7,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = 9,
                            BusinessId = 8,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AppUserId = 10,
                            BusinessId = 8,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            AppUserId = 10,
                            BusinessId = 9,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            AppUserId = 11,
                            BusinessId = 10,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            AppUserId = 7,
                            BusinessId = 10,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            AppUserId = 7,
                            BusinessId = 11,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            AppUserId = 8,
                            BusinessId = 12,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            AppUserId = 9,
                            BusinessId = 12,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            AppUserId = 9,
                            BusinessId = 13,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            AppUserId = 10,
                            BusinessId = 14,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            AppUserId = 11,
                            BusinessId = 14,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            AppUserId = 11,
                            BusinessId = 15,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            AppUserId = 7,
                            BusinessId = 16,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            AppUserId = 8,
                            BusinessId = 16,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            AppUserId = 8,
                            BusinessId = 17,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            AppUserId = 9,
                            BusinessId = 18,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            AppUserId = 10,
                            BusinessId = 18,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            AppUserId = 10,
                            BusinessId = 19,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            AppUserId = 11,
                            BusinessId = 20,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            AppUserId = 7,
                            BusinessId = 20,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            AppUserId = 7,
                            BusinessId = 21,
                            Comment = "Çok memnun kaldım, teşekkürler!",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            AppUserId = 8,
                            BusinessId = 22,
                            Comment = "Hizmet kalitesi güzeldi.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            AppUserId = 9,
                            BusinessId = 22,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            AppUserId = 9,
                            BusinessId = 23,
                            Comment = "Kesinlikle tavsiye ederim.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            AppUserId = 10,
                            BusinessId = 24,
                            Comment = "Gayet profesyonel bir işletme.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            AppUserId = 11,
                            BusinessId = 24,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            AppUserId = 11,
                            BusinessId = 25,
                            Comment = "Tekrar geleceğim, memnun kaldım.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessLocations", (string)null);
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("BusinessLogos");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessPhotos", (string)null);
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessRatings");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentCustomers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("ServiceContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BusinessServices");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PackageType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsedForBusinessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UsedForBusinessId")
                        .IsUnique();

                    b.HasIndex("AppUserId", "IsUsed", "PaymentStatus");

                    b.ToTable("BusinessSlots");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OtherUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("\"AppointmentId\" IS NOT NULL");

                    b.HasIndex("ConversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("AppUserId", "BusinessId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUserInformation", "AppUserInformation")
                        .WithOne()
                        .HasForeignKey("Randevu365.Domain.Entities.AppUser", "AppUserInformationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUserInformation");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Appointments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.BusinessService", "BusinessService")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Business");

                    b.Navigation("BusinessService");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Business", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Businesses")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessComment", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("BusinessComments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessComments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessHour", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessHours")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessLocation", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessLocations")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessLogo", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithOne("BusinessLogo")
                        .HasForeignKey("Randevu365.Domain.Entities.BusinessLogo", "BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessPhoto", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessPhotos")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessRating", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("BusinessRatings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessRatings")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessService", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("BusinessServices")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessSlot", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("BusinessSlots")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.Business", "UsedForBusiness")
                        .WithOne()
                        .HasForeignKey("Randevu365.Domain.Entities.BusinessSlot", "UsedForBusinessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("UsedForBusiness");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Conversation")
                        .HasForeignKey("Randevu365.Domain.Entities.Conversation", "AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Randevu365.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Favorites")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevu365.Domain.Entities.Business", "Business")
                        .WithMany("Favorites")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BusinessComments");

                    b.Navigation("BusinessRatings");

                    b.Navigation("BusinessSlots");

                    b.Navigation("Businesses");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BusinessComments");

                    b.Navigation("BusinessHours");

                    b.Navigation("BusinessLocations");

                    b.Navigation("BusinessLogo");

                    b.Navigation("BusinessPhotos");

                    b.Navigation("BusinessRatings");

                    b.Navigation("BusinessServices");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("Randevu365.Domain.Entities.BusinessService", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
